### ISSUE TITLE
Move runspec from automated scripts to dxapp.json

### ISSUE THREAD

**Issue by RachelDuffin** [moka-guys/dnanexus_FH_PRS#5]
The runspec input in the automated scripts 'mokapipe_fh_gatk_timeout_args' is a runspec input and instead of being a command line input should be located in the dxapp.json file within this repository.

```
"runSpec": {
         |     "executionPolicy": {
         |        "restartOn": {
         |          "JobTimeoutExceeded": 1,
                    "JMInternalError": 1,
                    "UnresponsiveWorker": 2,
                    "ExecutionError": 1
         |        }
         |     },
         |     "timeoutPolicy": {
         |        "*": {
         |          "hours": 12
         |        }
         |     },
```

**Comment by isabelrem** [comment]
Was this comment meant for the fh prs app, or made in error?

**Comment by RachelDuffin** [comment]
Yes this was meant for this app - you can add these settings to the dxapp.json file - see some of the other nexus apps in github for other examples

**Comment by RachelDuffin** [comment]
Not needed - this is for the GATK app rather than this app. Apologies!
